---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "sales.shipping.shipping-dev.shipping-dev1"
spec:
  capacity:
    storage: "10Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - rw
    - sync
  nfs:
    path: "/k8s-static-volumes/sales/shipping/shipping-dev/"
    server: "fs-08faf1e99e00ac435.efs.us-east-1.amazonaws.com"
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "shipping-dev1"
  namespace: "shipping-dev"
spec:
  resources:
    requests:
      storage: "10Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: "sales.shipping.shipping-dev.shipping-dev1"